[package]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "Extra utilities for axum"
edition = "2018"
homepage = "https://github.com/tokio-rs/axum"
keywords = ["http", "web", "framework"]
license = "MIT"
name = "axum-extra"
readme = "README.md"
repository = "https://github.com/tokio-rs/axum"
version = "0.1.2"

[features]
default = []
erased-json = ["serde_json", "serde"]
typed-routing = ["axum-macros", "serde", "percent-encoding"]
opentelemetry = [
    "axum/matched-path",
    "axum/original-uri",
    "opentelemetry-http",
    "opentelemetry-lib",
    "tower-http/request-id",
    "tower-http/trace",
    "tracing",
    "tracing-opentelemetry",
]

[dependencies]
axum = { path = "../axum", version = "0.4" }
bytes = "1.1.0"
http = "0.2"
mime = "0.3"
pin-project-lite = "0.2"
tower = { version = "0.4", default_features = false, features = ["util"] }
tower-http = { version = "0.2", features = ["map-response-body"] }
tower-layer = "0.3"
tower-service = "0.3"

# optional dependencies
axum-macros = { path = "../axum-macros", version = "0.1", optional = true }
opentelemetry-http = { version = "0.6", optional = true }
opentelemetry-lib = { package = "opentelemetry", version = "0.17", optional = true }
percent-encoding = { version = "2.1", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0.71", optional = true }
tracing = { version = "0.1", optional = true }
tracing-opentelemetry = { version = "0.17", optional = true }

[dev-dependencies]
assert-json-diff = "2.0"
axum = { path = "../axum", version = "0.4" }
http-body = "0.4"
hyper = "0.14"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.14", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
uuid = { version = "0.8", features = ["v4"] }

[package.metadata.docs.rs]
all-features = true
rustdocflags = ["--cfg", "docsrs"]
